apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-auth
  template:
    metadata:
      labels:
        app: node-auth
    spec:
      containers:
      - name: node-auth
        image: pavankumar213/node-auth-app:latest
        ports:
        - containerPort: 5000
